# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4735378d125554acf62d40e13d3f00587d88f1540dd5889786e5f59e3c6fa90b735e8f67f338feefd29678b392e4ced73c591392f2bd30d9117cfd3d6323ecde

test:
  secret_key_base: 8eeac8a8c6ed7b6f812d7491102682068622ff1f824f0cbd74be5c1387b64ca749c3fa0282055bef87757367f32b48b342c71541ca71b42a3fcb6fc2c31e3df2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
